import { EVENT_TYPES, RECORD_TYPES } from "../../core/constants.js";
import { ERROR_CODES, ModuleError } from "../../core/errors.js";
import { hasCapability } from "../../core/management-contracts.js";
import { updateRecord } from "../../data/journal-store.js";
import { recordIndex } from "../../data/record-index.js";
import { decodeRecord } from "../../models/record-codec.js";
import { normalizeIntelRemovePayload, normalizeIntelRevealPayload, normalizeIntelUpsertPayload } from "./contracts.js";

function resolve(reference,expectedType){ const byId=reference?.entityId?recordIndex.getByEntityId(reference.entityId):null; const byUuid=reference?.uuid?recordIndex.get(expectedType,reference.uuid):null; if(byId&&byUuid&&byId.uuid!==byUuid.uuid) throw new ModuleError(ERROR_CODES.CONFLICT,"A referência aponta para UUID e entityId de entidades diferentes."); const doc=byId??byUuid; if(!doc) throw new ModuleError(ERROR_CODES.NOT_FOUND,`${expectedType} não encontrado.`); const r=decodeRecord(doc); if(r.recordType!==expectedType) throw new ModuleError(ERROR_CODES.VALIDATION,`Registro não é ${expectedType}.`); return r; }
function assertGM(callerUserId){ const u=game.users.get(callerUserId); if(!u?.isGM) throw new ModuleError(ERROR_CODES.PERMISSION,"Apenas GM pode alterar inteligência persistente."); }
function ref(record){ return {recordType:record.recordType,uuid:record.uuid,entityId:record.data.entityId}; }
function assertIntel(domain){ if(!hasCapability(domain.data,"intel")) throw new ModuleError(ERROR_CODES.VALIDATION,`O Domain '${domain.document.name}' não possui capability intel.`); }

export async function executeIntelUpsert({payload,callerUserId}){
  assertGM(callerUserId); const n=normalizeIntelUpsertPayload(payload); const domain=resolve(n.domain,RECORD_TYPES.DOMAIN); assertIntel(domain); const target=n.targetDomain?resolve(n.targetDomain,RECORD_TYPES.DOMAIN):null; const before=foundry.utils.deepClone(domain.data); const data=foundry.utils.deepClone(domain.data); data.intel??=[];
  const idx=n.localId?data.intel.findIndex((i)=>i.localId===n.localId):-1; const localId=idx>=0?data.intel[idx].localId:(n.localId||`intel_${foundry.utils.randomID()}`); const entry={localId,title:n.title,category:n.category,visibility:n.visibility,targetDomain:target?ref(target):null,content:n.content,credibility:n.credibility,source:n.source,revealed:n.revealed,tags:n.tags}; if(idx>=0)data.intel[idx]=entry; else data.intel.push(entry);
  const updated=await updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data}); return {result:{domainEntityId:updated.data.entityId,intel:entry},entities:[updated.data.entityId,target?.data.entityId].filter(Boolean),events:[{type:EVENT_TYPES.INTEL_UPDATED,entities:[updated.data.entityId],payload:entry}],rollback:()=>updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data:before})};
}
export async function executeIntelRemove({payload,callerUserId}){ assertGM(callerUserId); const n=normalizeIntelRemovePayload(payload); const domain=resolve(n.domain,RECORD_TYPES.DOMAIN); assertIntel(domain); const before=foundry.utils.deepClone(domain.data); const data=foundry.utils.deepClone(domain.data); const found=(data.intel??[]).find((i)=>i.localId===n.localId); if(!found) throw new ModuleError(ERROR_CODES.NOT_FOUND,"Intel não encontrada."); data.intel=(data.intel??[]).filter((i)=>i.localId!==n.localId); const updated=await updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data}); return {result:{domainEntityId:updated.data.entityId,localId:n.localId},entities:[updated.data.entityId],events:[{type:EVENT_TYPES.INTEL_REMOVED,entities:[updated.data.entityId],payload:{localId:n.localId}}],rollback:()=>updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data:before})}; }
export async function executeIntelReveal({payload,callerUserId}){ assertGM(callerUserId); const n=normalizeIntelRevealPayload(payload); const domain=resolve(n.domain,RECORD_TYPES.DOMAIN); assertIntel(domain); const before=foundry.utils.deepClone(domain.data); const data=foundry.utils.deepClone(domain.data); const idx=(data.intel??[]).findIndex((i)=>i.localId===n.localId); if(idx<0) throw new ModuleError(ERROR_CODES.NOT_FOUND,"Intel não encontrada."); data.intel[idx]={...data.intel[idx],visibility:"public",revealed:true}; const updated=await updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data}); return {result:{domainEntityId:updated.data.entityId,intel:updated.data.intel[idx]},entities:[updated.data.entityId],events:[{type:EVENT_TYPES.INTEL_REVEALED,entities:[updated.data.entityId],payload:{localId:n.localId}}],rollback:()=>updateRecord({uuid:domain.uuid,recordType:RECORD_TYPES.DOMAIN,data:before})}; }
